name: Product Service

on:
  push:
    branches: ["master"]
    paths:
      - "src/services/product-service/**"

  pull_request:
    branches: ["master"]
    paths:
      - "src/services/product-service/**"

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml
    with:
      service-path: ./src/services/product-service
